### ISSUE TITLE
CMD usage

### ISSUE THREAD

**Issue by gystar** [tree-sitter/tree-sitter-graph#127]
Hi, guys!
I want to know how to convert an AST file (generated by the tree-sitter) to a graph file for visualization.
I find the CMD of the tree-sitter-graph needs tsg file and source file. but I do not know what is the tsg file and how to write it.
Can you present an exact example? The best format of output should be DOT.

**Comment by robrix** [comment]
The tsg file is a program specifying what nodes should be constructed given some specific AST. [Its documentation is reasonably thorough](https://docs.rs/tree-sitter-graph/0.9.1/tree_sitter_graph/reference/), but you may wish to see [examples from the tests](https://github.com/tree-sitter/tree-sitter-graph/blob/3ce18ad99546c8e0cae016b2bee4181108586f3f/tests/it/execution.rs#L63-L73) or [part of our code navigation service](https://github.com/github/stack-graphs/blob/main/languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg).

I don't believe `tree-sitter-graph` offers DOT output at present. We typically use it by linking against it as a library and inspecting the resulting graph in memory, but the `--json` output flag was added to support more workflows wishing to use it as a separate tool, if you'd prefer that. It formats the graph as an adjacency list.
