### ISSUE TITLE
what do the graphs look like?

### ISSUE THREAD

**Issue by ghost** [tree-sitter/tree-sitter-graph#129]

**Comment by robrix** [comment]
That's really up to the rules you make. E.g. an empty set of rules produces an empty graph—not terribly exciting. You can also painstakingly duplicate the AST if you want, or, much more likely, make a more interesting graph (perhaps with sharing or maybe even cycles).

I think beyond that the only really general statements I can make are:

- they're directed
- vertices and edges can have named attributes which can act as labels
- there can be at most one edge between the same (ordered) pair of vertices

Not sure if that answers your question?

**Comment by croshay** [comment]
do you have some examples?

**Comment by Jakobeha** [comment]
I assume graphs for static analysis, like:

- [Control-flow Graphs (CFGs)](https://en.wikipedia.org/wiki/Control-flow_graph) ([example on page 6](https://groups.seas.harvard.edu/courses/cs153/2018fa/lectures/Lec17-CFG-dataflow.pdf))
- [Data-flow](https://en.wikipedia.org/wiki/Data-flow_analysis) [Graphs (DFGs)](http://bears.ece.ucsb.edu/research-info/DP/dfg.html) ([image](https://github.com/tree-sitter/tree-sitter-graph/assets/32147996/0e151269-8651-4be2-a264-9959e13b9c78))
- [Dominator](https://en.wikipedia.org/wiki/Dominator_(graph_theory)) [Trees](https://llvm.org/devmtg/2017-10/slides/Kuderski-Dominator_Trees.pdf)
- [Dependence Graphs](https://home.cs.colorado.edu/~kena/classes/5828/s99/lectures/lecture25.pdf)

These are built from ASTs; but building them is quite complicated [1], and the algorithm is different for programs with different control structures, hence this DSL.

[1] See [this guide to constructing a CFG from source code](https://stackoverflow.com/a/51113472), constructing a dominator tree and dependence graph requires a CFG first

**Comment by hendrikvanantwerpen** [comment]
I think this question has been sufficiently answered, given the generality of the question. (And thanks @Jakobeha  for the pointers on possible graph based analyses!)

I'm closing this now. If you want to discuss this further, opening a discussion (instead of an issue) is the best way.
