### ISSUE TITLE
Empty files do not produce graphs

### ISSUE THREAD

**Issue by NinoScript** [tree-sitter/tree-sitter-graph#157]
Currently, empty source files are ignored and do not produce any nodes, even if a stanza captures the root syntax node.
Having anything in the source file, like a single `\n` for example, makes it work.

**Comment by NinoScript** [comment]
The Iterator implementation for QueryMatches returns no item when the source is `""`, so the stanza is never run.
https://github.com/tree-sitter/tree-sitter-graph/blob/68504d72049b131064941fff105e5deaf8ea7074/src/execution/lazy.rs#L123-L127

Because in `tree-sitter-0.20.10/binding_rust/lib.rs`, `ffi::ts_query_cursor_next_match` returns false immediately.
```rust
impl<'a, 'tree, T: TextProvider<'a>> Iterator for QueryMatches<'a, 'tree, T> {
    type Item = QueryMatch<'a, 'tree>;

    fn next(&mut self) -> Option<Self::Item> {
        unsafe {
            loop {
                let mut m = MaybeUninit::<ffi::TSQueryMatch>::uninit();
                if ffi::ts_query_cursor_next_match(self.ptr, m.as_mut_ptr()) {
                    let result = QueryMatch::new(m.assume_init(), self.ptr);
                    if result.satisfies_text_predicates(
                        self.query,
                        &mut self.buffer1,
                        &mut self.buffer2,
                        &mut self.text_provider,
                    ) {
                        return Some(result);
                    }
                } else {
                    return None;
                }
            }
        }
    }
}
```

For now, I'm mitigating this in my project by passing `"\n"` instead of the file, if the file is empty.

**Comment by hendrikvanantwerpen** [comment]
This is indeed the result of Tree-sitter's behavior. As such, it is not a TSG issue, and I'll close this.

Consider reporting an issue on TS itself though (if that hasn't happened before). I agree that that behavior is unexpected.
