### ISSUE TITLE
More docs and demo

### ISSUE THREAD

**Issue by cyw3** [tree-sitter/tree-sitter-graph#39]
Hi,
it is a good project.

However, can you provide more docs and demo?

Thank you!

**Comment by InTheCloudDan** [comment]
hey @patrickt I'm trying to read up on it and `stack-graphs` and there appears to be a lot of implied knowledge how things work. I've made a bit of progress by looking at this https://github.com/github/stack-graphs/pull/72/files#diff-1251236b0629a8f9348372ab00c4b86ad7e42cab3aa8ec32e56f7b2fb0ff8f2eR4 but I'm unsure of how the `.tsg` file was generated using the `tree-sitter-go` grammar.

**Comment by hendrikvanantwerpen** [comment]
Hi! We realize that the lack of documentation and tooling is currently an obstacle to get started with stack graphs. We are actively working to remedy that! I cannot give you a precise time frame, but we hope to be able to put out more on that in the near future.

**Comment by augmented-fog** [comment]
Do you have are more specific suggestion regarding what is lacking documentation?
I think crate docs may benefit from providing additional details.
The tests included with each crate are at the moment the best way to understand how to consume this project when crate documentation is missing.

**Comment by hendrikvanantwerpen** [comment]
Closing this as stale. Since the discussion seems more related to stack graphs, I suggest opening a discussion on https://github.com/github/stack-graphs if you want to discuss this further.
