### ISSUE TITLE
Trying to understand more about tsg-files and the orchestration between the projects

### ISSUE THREAD

**Issue by ProgHaj** [tree-sitter/tree-sitter-graph#42]
Hello!

I recently came into contact with the world of stack-graph and everything related. I really like the ease of usage of tree-sitter as well as I think I've begun to understand the connection between tree-sitter, tree-sitter-graph and stack-graph. 
I read that the python-dsl bindings for tree-sitter-graph hasn't yet been released, so I though of creating a very simplistic version to use for myself in the meantime. What I'm trying to build is a simple goto functionality combining the three libs -- my first iteration doesn't need to be perfect. 
I have some questions I would love to have answered.

1. I began looking into creating tsg-files, the only documentation I found on how to write them was in src/reference/mod.rs. My question would be: Can you combine scm-querries with tsg-querries? E.g., is there a way to use scm-querries as the first part to set up identifiers and then use tsg-querries on some of the scm but not all of them? I'm not sure if that functionality would help or not, or if I just need to understand the DSLs better. 

2. My current thought on the workflow is: 
    1. Use tree-sitter docs to aid creating scm-querries that finds all relevant scopes + all function calls and imports in a file.
    2. Further expand on the scm querries from 1., modify each scm-query to a tsg-query. Tag each scope with the parent scope + current scope, as well as finding source and sink of imports and function calls.
    3. Use the output of tsg in stack-graph to create a graph, using the example-code in stack-graphs/tests/it/test_graphs/cyclic_imports_python.rs as aid. Make sure to build up the graph using the scopes obtained in 2.
    4. Use stack-graph partial-path functionality to find the path from caller-source to call-location
   
 Does that seem to be correct way of thinking about how to combine the tools?

3. Can a tsg-file consist of a "tagging-step" to give attributes to each mapping, and then after a matching-step where the attributes set is consumed? E.g. tag each found scope with it's parent scope + current-scope, then afterwards only use the ones matched against function-calls.

Sorry if the questions have been answered before or if they doesn't make sense, just trying to grasp my head around everything.
I love the work you're doing, it's a really interesting project!

**Comment by hendrikvanantwerpen** [comment]
Hi! We realize that the lack of documentation and tooling is currently an obstacle to get started with stack graphs. We are actively working to remedy that! I cannot give you a precise time frame, but we hope to be able to put out more on that in the near future.

**Comment by hendrikvanantwerpen** [comment]
I'm closing this as stale. If you're still interested in these questions, I suggest opening a discussion in https://github.com/github/stack-graphs, which is a better place for these high level questions.
