### ISSUE TITLE
Should the JSON CLI flag take a path to output to instead of always using stdout?

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-graph#47]
Right now we always output to `stdout` and require users to redirect or pipe in their shell. It might be convenient to give an output path and use `--json -` or `--json /dev/stdout` to replicate the current behaviour.

**Comment by hendrikvanantwerpen** [comment]
I would say having a flag is a must if any of :
- multiple outputs are produced in one run (e.g., human-readable feedback and json)
- multiple files are processed in one run

(There might be more good reasons that I'm forgetting.) I think neither of these are currently the case, so I can go either way on this. If you add the flag, I think supporting `--json -` is nice!
