### ISSUE TITLE
Doc link dead

### ISSUE THREAD

**Issue by Symbolk** [tree-sitter/tree-sitter-graph#5]
Hi, I am very interested in this project, however, the doc link seems dead:
https://docs.rs/tree-sitter-graph/

![image](https://user-images.githubusercontent.com/14107297/120253446-ee702f80-c2b9-11eb-90b1-a7075c00954d.png)

**Comment by dcreager** [comment]
Hi sorry for missing this, I wasn't watching the repo for some reason!

The docs link should work now, we've published an initial version of the crate.  It only contains the reference documentation of the DSL that we're aiming for, the implementation is still in the process of being written and reviewed.
