### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by Malibushko** [tree-sitter/tree-sitter-graph#53]
Hi. I see that the whole project is written in Rust and so I wanted to ask if there are any plans to add a C API in the future?

**Comment by robrix** [comment]
We haven't got any plans to at the moment, no, and I don't think we're quite ready to commit to any stable internal API yet. That said, if you've got a specific use case in mind, we might be able to provide some advice.

**Comment by rupurt** [comment]
I'd absolutely love to use this library as part of a transpilation toolkit created in C
