### ISSUE TITLE
Bad error message (and possible execution bug?) with typo

### ISSUE THREAD

**Issue by jorendorff** [tree-sitter/tree-sitter-graph#67]
The .tsg below has two bugs:
1. Typo on line 3 (`@ehre` should be `@here`)
2. Use of `@path.context` on line 10 which is never defined on that syntax node

```
[
  (struct_item name: (_) @here)
  (enum_item name: (_) @ehre) ;; oops, typo
] {
  let @here.context = "%pattern"
}

(scoped_type_identifier) @path {
  node s
  attr (s) symbol = @path.context ;; oops, not defined
}
```

I ran it on this test case.

```rust
pub enum A {
    M(std::string::String),
}
```

**Expected behavior:** Either some error message for bug 1, or the usual message for bug 2 (`Undefined scoped variable [syntax node scoped_identifier (2, 7)].context`)

**Actual behavior:**

```
$ ./bin/tree-sitter-stack-graphs test --grammar . --tsg ./bug.tsg ./testcase.rs
Error: Error running test ./testcase.rs

Caused by:
    0: Executing attr ((load 1)) symbol = (scoped [syntax node scoped_type_identifier (2, 7)] 'context) at (10, 3)
    1: Expected a syntax node  got #null
```

This seems like a bug to me because I can't think of any legit way for `#null` to get into the computation at line 10.

**To reproduce:**

```
git clone git@github.com:jorendorff/tree-sitter-rust.git
cd tree-sitter-rust
git checkout jorendorff/internal-error
script/setup
./bin/tree-sitter-stack-graphs test --grammar . --tsg ./bug.tsg ./testcase.rs
```

**Comment by hendrikvanantwerpen** [comment]
So far I discovered that the error message is very misleading. It reports at line 10, which is the use site, but the error is coming from the definition site at line 5, where `@here` is `#null` because of the typo. The error is only detected when `.context` is forced, but the context where the lazy variable is set is lost and not reported as it should.

**Comment by hendrikvanantwerpen** [comment]
The change in #68 now produces the following error message:

```
Caused by:
    0: Executing attr ((load 1)) symbol = (scoped [syntax node scoped_type_identifier (2, 7)] 'context) at (10, 3)
    1: Evaluating scope of variable _.context set at (5, 13)
    2: Expected a syntax node got #null
```

This can still be improved upon, I think, but it's a start.

**Comment by hendrikvanantwerpen** [comment]
Note that this is fixed here, but it will take a few more steps before this shows up in `tree-sitter-stack-graphs`.
