### ISSUE TITLE
Example TSG files for languages?

### ISSUE THREAD

**Issue by InTheCloudDan** [tree-sitter/tree-sitter-graph#71]
I tried piecing together a python tsg file from https://docs.rs/tree-sitter-graph/0.5.1/tree_sitter_graph/reference/ but I get errors:

```
Caused by:
    0: Invalid query pattern: [0, "string", 0, #true, @id]
        ^
    1: Query error at 7:2. Invalid syntax:
       [0, "string", 0, #true, @id]```

Is there a full tsg file available for any languages to make it a bit easier to get started testing out functionality?

**Comment by InTheCloudDan** [comment]
@hendrikvanantwerpen thanks for that, when I try the python one I'm getting:
```Caused by:
    0: Executing edge @this.node -> @arg.node at (54, 3)
    1: Undefined variable @arg.node on node [syntax node attribute (4, 7)]```
    
I was using it with the example python file provided in the link above:
```
from one.two import d, e.c
import three
print(d, e.c)
print three.f
```

**Comment by hendrikvanantwerpen** [comment]
How are you executing the file? There are two possible issues:
1. The rules assume lazy execution and you are not passing the `-z` flag to `tree-sitter-graph`.
2. You are using constructs that are not covered by the rules in the TSG. This file is very limited, and it looks like the `attribute` node type has no rule, so the `.node` scoped variable is never created on it.

**Comment by InTheCloudDan** [comment]
thanks @hendrikvanantwerpen! It looks like I'm using constructs that aren't covered by rules, this has helped me make a lot of progress in getting parsing started.
